version: "3"

services:
  db:
    image: mysql
    container_name: mysql-database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "fimeco_database"
    volumes:
      - ./schemas:/var/lib/mysql
